### PR TITLE
Update 6.0/stable, 6.0/sc and 6.1/testing versions

### PR DESCRIPTION
**Pull request by fharbe**
Changes proposed in this pull request:

- Update 6.0/stable to 6.0.28
- Update 6.0/sc to 6.0.28-39f3b98a31
- Update 6.1/testing to 6.1.20-07a45f3da7
- Tag 6.0.28 release (9a7233ff864f515e362a67d03106b0627ff835c1)

@goofball222

### CODE REVIEW

**Comment by fharbe** [comment]
I noticed I forgot to update the README and CHANGELOG, I'll update the pull request accordingly :wink:

**Comment by fharbe** [comment]
Sorry for force-pushing two times, this is one of my very first contributions on GitHub and I thought a clean repository history would be nice when you accept the PR :slightly_smiling_face: :angel:

**Comment by goofball222** [comment]
Appreciate the PR!

**Comment by fharbe** [comment]
Thanks! :slightly_smiling_face:

**Pull request merged**
